version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/notification-server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 180
      runas: ubuntu